project_id = "kngievscfzjpfgrpdxcc"

[functions.send-email]
verify_jwt = false


[functions.parse-obligations]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.mercadopago]
verify_jwt = false

[functions.create-user]
verify_jwt = false

